### PR TITLE
Move from SAPI to DWMC

### PR DESCRIPTION
**Pull request by ccoffrin**
Address #6 to a large extent.

### CODE REVIEW

**Comment by ccoffrin** [comment]
@arcondello, @bellert any suggestions?

**Comment by ccoffrin** [comment]
Note, need to make sure the docs are updated before merging this.

**Comment by bellert** [comment]
Hi @ccoffrin, this looks good to me. I just checked out your master and this PR and ran them both with `python dwig.py -hcd 16 ran` and it seemed fine at first glance. Have you tried https://github.com/dwavesystems/dwave_micro_client_dimod? The dimod interface (https://github.com/dwavesystems/dimod) abstracts a bit of the details away and makes things easier.

**Comment by ccoffrin** [comment]
Thanks for the suggestion @bellert, I had a quick look at dimod (but not dwave_micro_client_dimod yet). The documentation on dimod seemed pretty thin, so I had a hard time understanding how to use it. 

That said, I am not sure dimod is the right abstraction for this tool. The primary goal of dwig is to generate inputs for a specific d-wave QPU.  It does not submit any jobs or do any sampling.

**Comment by arcondello** [comment]
Hey @ccoffrin , I agree the documentation is thin, you caught us in the middle of a major overhaul! I also agree that (for now) using the micro client directly is more appropriate. In the long run it might make sense to make the switch, if only because we're hoping over time to increment the version of the REST API more aggressively, and the micro client will track that quite closely, while dimod will stay more consistent.

**Comment by ccoffrin** [comment]
FYI @yuchenpang, I am planning on merging this into master in the next day or so after some longer regression tests finish.  The SAPI library is no longer required, it has been replaced by dwave-cloud-client and dwave-networkx.  This changes how hardware config files are managed as well as, we will use the config file format of dwave-cloud-client.

Also works on python 3, ftw!

**Pull request merged**
